FROM python:3.8-buster

WORKDIR /usr/app

RUN apt-get update

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt

COPY ./app.py .

ENV FLASK_APP app.py
ENV FLASK_ENV development

CMD [ "python3", "-m", "flask", "run", "--host=0.0.0.0" ]

