version: "3.8"

services:
        app:
                build:
                        context: ./
                        dockerfile: Dockerfile.dev
                volumes:
                        - ./:/usr/app
                ports:
                        - 5000:5000
                restart: unless-stopped
